---
- name: Attempt to call another playbook
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    az_resource_group: Demo-CloudTools-rg
    az_vnet_resource_group: gitlab_demo_lab
    az_location: uksouth
    az_vnet_name: gitlab_lab_net
    az_vnet_prefixes: "10.0.0.0/16"
    az_subnet_name: "infra"
    az_subnet_prefix: "10.0.1.0/24"
    az_publicipaddress_method: 'Static'
    az_securitygroup_rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    az_base_name: 'buildtest1'
    az_virtualmachine_name: "{{ az_base_name }}"
    az_networkinterface_name: "{{ az_base_name }}Nic"
    az_publicipaddress_name: "{{ az_base_name }}Pip"
    az_securitygroup_name: "{{ az_base_name }}Nsg"
    az_virtualmachine_size: 'Standard_B2s'
    az_managed_disk_type: "Standard_LRS"
    az_admin_username: 'cloud_user'
    az_ssh_password_enabled: 'False'
    az_ssh_private_key: "~/.ssh/cloud_user_id_rsa"
    az_ssh_public_key: "~/.ssh/cloud_user_id_rsa.pub"
    az_vm_tags:
      build_test: "{{ lookup('env', 'CI_BUILD_ID') }}"
      os: 'linux'
    az_image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.6'
      version: latest
    verbosity_level: 0

  pre_tasks:

  - name: get resource group facts
    azure_rm_resourcegroup_facts:
      name: "{{ az_resource_group }}"
    register: azure_resourcegroup_facts
    tags:
      - azure_rm_resourcegroup
      - azure_rm_resourcegroup_facts

  - name: Debug azure_resourcegroup_facts
    debug:
      var: azure_resourcegroup_facts
      verbosity: "{{ verbosity_level }}"
    tags:
      - azure_rm_resourcegroup
      - azure_rm_resourcegroup_facts

  - name: Debug azure_resourcegroup
    debug:
      var: azure_resourcegroup_facts
      verbosity: "{{ verbosity_level }}"
    tags:
      - azure_rm_resourcegroup

  - name: Get virtual network
    azure_rm_virtualnetwork_facts:
      resource_group: "{{ az_vnet_resource_group }}"
      name: "{{ az_vnet_name }}"
    register: azure_virtualnetwork
    tags:
      - azure_rm_virtualnetwork

  - name: Debug azure_virtualnetwork
    debug:
      var: azure_virtualnetwork
      verbosity: "{{ verbosity_level }}"
    tags:
      - azure_rm_virtualnetwork

  - name: Create a network interface
    azure_rm_networkinterface:
      name: "{{ az_networkinterface_name }}"
      resource_group: "{{ az_resource_group }}"
      virtual_network: "{{ azure_virtualnetworks[0].id }}"
      subnet_name: "{{ azure_virtualnetworks[0].properties.subnets[0].name }}"
    register: azure_networkinterface
    tags:
      - azure_rm_networkinterface

  - name: Debug azure_networkinterface
    debug:
      var: azure_networkinterface
      verbosity: "{{ verbosity_level }}"
    tags:
      - azure_rm_networkinterface

  - name: Create a VM
    azure_rm_virtualmachine:
      resource_group: "{{ az_resource_group }}"
      name: "{{ az_virtualmachine_name }}"
      vm_size: "{{ az_virtualmachine_size }}"
      admin_username: "{{ az_admin_username }}"
      ssh_password_enabled: false
      ssh_public_keys:
      - path: "/home/{{ az_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ lookup('env', 'SSH_PUB_KEY') }}"
      network_interfaces: "{{ az_networkinterface_name }}"
      managed_disk_type: "{{ az_managed_disk_type }}"
      image: "{{ az_image }}"
      tags: "{{ az_vm_tags }}"
    register: azure_virtualmachine
    tags:
      - azure_rm_virtualmachine

  tasks:

    - name: Set target variable
      set_fact:
        target: "{{ lookup('env', 'ANSIBLE_TARGET') }}_{{ lookup('env', 'CI_BUILD_ID') }}"

    - name: Debug target variable
      debug:
        var: target



- name: Include tasks to execute
  hosts: "{{ hostvars['localhost']['target'] }}"
  gather_facts: no

  pre_tasks:

  - name: Refresh inventory to ensure new instace will be picked up
    meta: refresh_inventory

  - name: wait for VMs
    wait_for_connection:
      timeout: 300

  - name: Now gather facts
    setup:

  tasks:

    - name: Import test tasks
      include_tasks: test.yml

