---
- name: Attempt to call another playbook
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Set target variable
      set_fact:
        target: "{{ lookup('env', 'ANSIBLE_TARGET') }}"

    - name: Debug target variable
      debug:
        var: target

- name: Include tasks to execute
  hosts: "{{ hostvars['localhost']['target'] }}"

  tasks:

    - name: Import test tasks
      include_tasks: test.yml

